### ISSUE TITLE
Managed to install it 

### ISSUE THREAD

**Issue by uhlhosting** [maruTA-bis5/mattermost-simple-lock-plugin#1]
I am a bit confused, how does this controls the servers, and or are this just informative messages, or is here a trick im missing.

**Comment by maruTA-bis5** [comment]
This is just informative.

I was wrote "Server-001" for example as usage.
You can also specify as TARGET_RESOURCE anything such as "Excel Workbook on shared folder".

If anyone already locked TARGET_RESOURCE, you can see "Resource [TARGET_RESOURCE] is already locked" ephemeral message.

**Comment by uhlhosting** [comment]
Can you share the locations of these files on server side after the plugin install?

**Comment by maruTA-bis5** [comment]
This plugin does not manage the actual location of the resource.
The user knows the location of the resource.

The background behind developing this plugin is as follows.

- In the office where I am working, there is a PC (OS: Windows 7 Professional) that is shared among multiple developers.
- This PC is connected to the LAN, we can log in with Windows Remote Desktop (mstsc.exe).
- With the limitations of Windows 7 Professional, only one user can log in at the same time.
- Before introducing Simple Lock, I was careful not to rob other users' login sessions by asking the administrator before logging in.
- In the absence of an administrator, it was necessary to call all the people using this PC and it was complicated.
- By introducing SImple Lock and executing `/lock (pc name)`, the above procedure became possible.
